---
title: "Sur le chemin de l'enf-R"
format:
  html:
    toc: false
---

{{< include _links.qmd >}}

```{r}
#| label: setup
#| include: FALSE
library(yaml)
library(stringr)
library(tibble)
library(dplyr)
library(purrr)
library(glue)
library(knitr)
library(kableExtra)
knitr::opts_chunk$set(echo = FALSE)
```

## Diapos

Quelques présentations pour s'initier à R.

::: {.callout-warning}
En anglais seulement, traduction à venir
:::

```{r}
schedule_df <- data.frame(
  topic = c("Introduction R", "Données avec R", "Intro modèle R"),
  weekno = 1:3
) %>%
  mutate(
    lecture = file.exists(sprintf("slides_r/lec_en-%.2d.qmd", weekno)),
  ) %>%
  mutate(
    slides = case_when(
      lecture == TRUE ~
        glue("<a class='fa fa-display' href='slides_r/{sprintf(\"lec_en-%.2d.slides.html\", weekno)}' target='_blank'></a> / <a class='fa fa-note-sticky' href='slides_r/{sprintf(\"lec_en-%.2d.notes.html\", weekno)}' target='_blank'></a>"),
      .default = NA
    ),
    topic = ifelse(is.na(topic), "", topic)
  ) %>%
  select(topic, slides)

schedule_df %>%
  kable(
    escape = FALSE, align = c("c", "c"),
    col.names = c(
      "Topic", "Slides"
    ),
    format = "html"
  ) %>%
  kable_styling(
    bootstrap_options = "striped",
    fixed_thead = T
  )
```

## Manuel

Et voila un manuel d'introduction à R: [Sur le chemin de l'enf-R][chemin_R] {{< fa thumbs-up >}} 
